packages:
  - apps/*
  - packages/**
  - "!**/__tests__/*"

catalog:
  "@types/node": ^22.15.2
  "@types/react-dom": ^19.1.2
  "@types/react": ^19.1.2
  lucide-react: ^0.503.0
  next: latest
  react-dom: ^19.1.0
  react: ^19.1.0
  typescript: ^5.8.3
  "@t3-oss/env-nextjs": ^0.13.0
