blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.tazeai.com
    about: For documentation and tutorials.
    about: For chatting with the community and getting help.