import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Providers } from './providers';
import '../styles/globals.css';
import { createI18nServerInstance } from '@/locales/i18n.server';
import { getTheme } from '@/libs/theme';
import { getFontsClassName } from '@/libs/fonts';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { language } = await createI18nServerInstance();
  const theme = await getTheme();
  const className = getFontsClassName(theme);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers lang="en">{children}</Providers>
      </body>
    </html>
  );
}
